name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

permissions:
  id-token: write
  packages: write
  contents: write
  pull-requests: write

jobs:
  publish:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    steps:
      - name: Create SHA Tag
        run: |
          git tag SHA-${GITHUB_SHA}
          git push origin SHA-${GITHUB_SHA}



